name: dart_serve_cli
description: A sample command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  path:
  args:
  analyzer:
  code_generator:
    git: https://github.com/gustavo-hillesheim/dart_code_generator

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

executables:
  dart_serve: dart_serve_cli
